### ISSUE TITLE
Windows 11 - Can not be opened

### ISSUE THREAD

**Issue by montogeek** [mbwilding/dygma-layer-switcher#9]
Hi!

Thanks for this! Unfortunately on Windows 11 is blocking its execution with the following message:
![image](https://github.com/mbwilding/dygma-layer-switcher/assets/1002461/ed0aeeb0-e789-4353-a5da-3411e243a737)

After that, it actually deletes the file from the folder.

**Comment by montogeek** [comment]
That happens even using "Run as administrador" option

**Comment by montogeek** [comment]
Information from Windows Security
![image](https://github.com/mbwilding/dygma-layer-switcher/assets/1002461/cbbe1445-2339-42b7-86f1-04d874877108)

The links takes you to https://www.microsoft.com/en-us/wdsi/threats/malware-encyclopedia-description?name=Trojan%3AScript%2FPhonzy.B!ml&threatid=2147772967

**Comment by montogeek** [comment]
In the Actions options, you can select "Allow on device", it won't restore the file automatically so you need to unzip it again but after that you can run it
![image](https://github.com/mbwilding/dygma-layer-switcher/assets/1002461/de8f3d55-8e86-4c02-aa25-afb2fe24b2be)

**Comment by mbwilding** [comment]
https://www.virustotal.com/gui/url/9a7486c49e4ce677e3255c03a6e1db8cce6aa94b570e8f6d23798d2d170b2818?nocache=1

I just did a virus total scan pulling the zip directly from GitHub. Sounds like you have an infection that is infecting newly aquired EXEs maybe? Hard to say but there's certainly no viruses in it.

I am running it on Windows 11, fully up to date.

**Comment by mbwilding** [comment]
It could also be defender misreporting, has been known to happen from time to time.
